# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

test_that("pop_type_destintation_countries works", {
  expect_true(inherits(pop_type_destintation_countries, "function")) 
})
