# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Population Type by Destination Countries 
#'
#' @param country1 Country Selection
#' @inheritParams ggplot2::ggplot
#'
#' @return
#' Graph
#' @export
#'
#' @examples
#' # Example with your data set in "inst/"
#' datafile_2 <- system.file("unhcr-situations.csv", package = "my.package")
#' unhcr_situations <- read.csv(datafile_2, encoding = "UTF-8")
#'
#' # Apply my function
#' pop_type_destintation_countries('Angola', 'zimbabwe', 'zambia')
pop_type_destintation_countries <- function(country1 = NULL,
                             country2 = NULL,
                             country3 = NULL,
                             country4 = NULL,
                             country5 = NULL){
  # Apply function
  df <- unhcr_situations |>
    select(Country, Individuals,Population.type)
  
  # Create a vector of countries to filter
  countries <- c(country1, country2, country3, country4, country5)
  countries <- countries[!is.null(countries)] # Remove NULL values
  countries <- tools::toTitleCase(countries) # Convert to Title case
  
  # Filter the data frame by the selected countries
  filtered_df <- df |>
    filter(Country %in% countries)
  
  box_p <- filtered_df |>
    ggplot2::ggplot(aes(x = Country,
                        y = Individuals,
                        fill = Population.type)) +
    geom_col()
    #geom_text(aes(label = Individuals))
    
  
  return(box_p)
}
